car_rent/car_rent/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from cars.views import index, about, cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('rent/', include('cars.urls', namespace='cars')),
    path('users/', include('users.urls', namespace='users')),
    path('about', about, name='about'),
    path('cart/', cart, name='cart'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rent/cars/urls.py
from django.urls import path
from cars.views import rent, cart_delete, page_car, price_view, services_view, conditions_view

app_name = 'cars'

urlpatterns = [
    path('', rent, name='index'),
    path('cart-delete/<int:cart_id>', cart_delete, name='cart_delete'),
    path('car/<int:car_id>', page_car, name='page_car'),
    path('price/', price_view, name='price'),
    path('services/', services_view, name='services'),
    path('conditions/', conditions_view, name='conditions'),
]

car_rent/users/urls.py
from django.urls import path
from users.views import login, register, user_profile, user_logout, rental_history, payment_view, delete_payment_method
from cars.views import return_car

app_name = 'users'

urlpatterns = [
    path('login', login, name='login'),
    path('registration', register, name='register'),
    path('profile', user_profile, name='profile'),
    path('logout', user_logout, name='logout'),
    path('rental_history', rental_history, name='rental_history'),
    path('return/<int:rental_id>/', return_car, name='return_car'),
    path('payment/', payment_view, name='payment'),
    path('payment/delete/<int:payment_id>/', delete_payment_method, name='delete_payment'),
]

car_rent/cars/models.py
from django.db import models
from users.models import User
from datetime import date
from django.utils import timezone
from django.conf import settings

# Create your models here.

# Модель - это и есть таблица

class CarClasses(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField()

    class Meta():
        verbose_name = 'Классы'
        verbose_name_plural = 'Классы'

    def __str__(self) -> str:
        return self.name

class CarBrands(models.Model):
    name = models.CharField(max_length=64, unique=True)

    class Meta():
        verbose_name = 'Бренды'
        verbose_name_plural = 'Бренды'

    def __str__(self) -> str:
        return self.name

class Cars(models.Model):
    brand = models.ForeignKey(CarBrands, on_delete=models.PROTECT)
    model = models.CharField(max_length=64)
    year = models.IntegerField()
    image = models.ImageField(upload_to='car_img', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    carClass = models.ForeignKey(CarClasses, on_delete=models.PROTECT)
    is_rented = models.BooleanField(default=False)
    color = models.CharField(max_length=64, null=True, blank=True)
    drive = models.CharField(max_length=64, null=True, blank=True)
    transmission = models.CharField(max_length=64, null=True, blank=True)
    power = models.IntegerField(null=True, blank=True)
    acceleration = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    engine_capacity = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)

    class Meta():
        verbose_name = 'Автомобили'
        verbose_name_plural = 'Автомобили'

    def __str__(self) -> str:
        return self.model

class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Cars, on_delete=models.CASCADE)
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(default=date.today)
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = 'Корзины пользователей'
        verbose_name_plural = 'Корзины пользователей'

    def total_days(self):
        if self.start_date == self.end_date:
            return (self.end_date - self.start_date).days + 1
        return (self.end_date - self.start_date).days

    def total_price(self):
        return self.total_days() * self.car.price
    
    @property
    def total(self):
        return self.total_days() * int(self.car.price)

    def __str__(self):
        return f"Корзина пользователя {self.user.username}"

class RentalHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Cars, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    rented_at = models.DateTimeField(auto_now_add=True)
    is_returned = models.BooleanField(default=False)
    
    class Meta():
        verbose_name = 'Истории аренды пользователей'
        verbose_name_plural = 'Истории аренды пользователей'

    def __str__(self):
        return f"История аренды {self.user.username} - {self.car.brand} {self.car.model}"

class CarImage(models.Model):
    car = models.ForeignKey('Cars', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='car_img')

    def __str__(self):
        image_name = self.image.name.rsplit('/')
        return f'Изображение "{image_name[1]}" для {self.car.model}'

    class Meta():
        verbose_name = 'Изображения автомобилей'
        verbose_name_plural = 'Изображения автомобилей'
    
class PaymentInfo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    card_number = models.CharField(max_length=16, verbose_name="Номер карты")
    card_holder = models.CharField(max_length=100, verbose_name="Имя владельца")
    expiry_date = models.DateField(verbose_name="Срок действия")
    payment_system = models.CharField(
        max_length=50, 
        choices=[
            ('visa', 'Visa'),
            ('mastercard', 'MasterCard'),
            ('mir', 'MIR'),
            ('paypal', 'PayPal'),
            ('yandex', 'Yandex Money'),
            ('qiwi', 'QIWI')
        ],
        verbose_name="Платёжная система"
    )
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = 'Способы оплаты пользователей'
        verbose_name_plural = 'Способы оплаты пользователей'

    def __str__(self):
        return f"{self.payment_system} - {self.card_number[-4:]}"

car_rent/cars/forms.py
from cars.models import Basket, Cars, PaymentInfo
from django import forms
from django.utils import timezone


class BasketForm(forms.ModelForm):
    class Meta:
        model = Basket
        fields = ['start_date', 'end_date']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date', 'min': timezone.now().date(), 'id': 'start_date'}),  # Минимум - сегодня
            'end_date': forms.DateInput(attrs={'type': 'date', 'min': timezone.now().date(), 'id': 'end_date'}),  # Минимум - сегодня
        }
    
    def clean_date(self, start_date, end_date):        
        if end_date < start_date:
            return False
        return True

class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=100,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите email'}))
    phone_number = forms.CharField(label='Номер телефона', max_length=15, widget=forms.TextInput(attrs={'class': 'form-control phone-number', 'placeholder': '+7 999 999 99 99'}))
    message = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}), required=False)

car_rent/cars/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.urls import reverse
from cars.models import CarClasses, Cars, CarBrands, Basket, RentalHistory
from cars.forms import BasketForm, ContactForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import datetime
from django.contrib import messages


# Create your views here.

services = [
            {'name': 'Фотосессия на фоне авто', 'description': 'Организуем профессиональную фотосессию с вашими любимыми автомобилями. Отличный выбор для особых событий или для создания уникального контента в социальных сетях.'},
            {'name': 'Аренда авто на мероприятие', 'description': 'Идеальное решение для свадьбы, корпоратива или любого другого важного события. Предоставим вам автомобиль, который подчеркнёт вашу важность на мероприятии.'},
            {'name': 'Трансфер в аэропорт', 'description': 'Удобный и быстрый трансфер в любой аэропорт. Мы заберем вас вовремя и доставим в нужное место с комфортом.'},
            {'name': 'Аренда автомобиля с водителем', 'description': 'Не хотите беспокоиться о вождении? Возьмите автомобиль вместе с опытным водителем, чтобы расслабиться и наслаждаться поездкой.'},
        ]

def index(request):
    context = {
        'cars': Cars.objects.order_by('brand').all(),
        'classes': CarClasses.objects.order_by('name').all(),
        'brands': CarBrands.objects.order_by('name').all(),
        'title': 'АрендаRzn',
        'services': services,
}
    return render(request, 'cars/index.html', context)

def rent(request):
    car_classes = CarClasses.objects.all()
    car_brands = CarBrands.objects.all()
    selected_class = request.GET.get('class')
    selected_brand = request.GET.get('brand')

    cars = Cars.objects.all().order_by('brand__name')

    print(cars)
    
    if selected_class and selected_class != 'all':
        cars = cars.filter(carClass__name=selected_class)

    if selected_brand and selected_brand != 'all':
        cars = cars.filter(brand__name=selected_brand)

    context = {
    'car_classes': car_classes,
    'car_brands': car_brands,
    'cars': cars,
    'selected_class': selected_class,
    'selected_brand': selected_brand,
    'title': 'Автопарк',
    }

    return render(request, 'cars/rent.html', context)

def about(request):
    context = {
        'title': 'О нас'
    }
    return render(request, 'cars/about.html', context)

@login_required
def cart(request):
    cart_items = Basket.objects.filter(user=request.user)
    total_price = sum([item.total_price() for item in cart_items])

    if request.method == 'POST':
        for item in cart_items:
            if item.start_date == item.end_date:
                end_date = item.end_date + datetime.timedelta(days=1)
            else:
                end_date = item.end_date
            RentalHistory.objects.create(
                user=request.user,
                car=item.car,
                start_date=item.start_date,
                end_date=end_date,
                total_price=item.total_price(),
            )
        cart_items.delete()
        return redirect('/users/rental_history')

    context = {
        'cart_items': cart_items,
        'total_price': total_price,
        'title': 'Корзина',
    }
    return render(request, 'cars/cart.html', context)



def cart_delete(request, cart_id):
    cart = Basket.objects.get(id=cart_id)
    car = cart.car
    car.is_rented = False
    car.save()
    cart.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# @login_required
def page_car(request, car_id):
    car = Cars.objects.get(id=car_id)
    images = car.images.all()
    start_date = request.POST.get('start_date')
    end_date = request.POST.get('end_date')

    if request.method == 'POST':
        form = BasketForm(data=request.POST)
        if form.clean_date(start_date, end_date):
            if form.is_valid():
                if not request.user.is_authenticated:
                    request.session['car_form_data'] = request.POST
                    request.session['car_id'] = car_id
                    return redirect(f'/users/login?next={request.path}')
            if car.is_rented == True:
                messages.error(request, 'Автомобиль уже забронирован.')
            else: 
                basket_item = form.save(commit=False)
                basket_item.user = request.user
                basket_item.car = car
                basket_item.added_at = timezone.now()
                basket_item.save()
                
                car.is_rented = True
                car.save()
                return redirect('cart')
        else:
            form.add_error('end_date', 'Конечная дата не может быть меньше')
    else:
        if 'car_form_data' in request.session and 'car_id' in request.session and request.session['car_id'] == car_id:
            form = BasketForm(request.session['car_form_data'])
            del request.session['car_form_data']
        else:
            form = BasketForm()

    context = {
        'car': car,
        'form': form,
        'car_images': images,
    }
    return render(request, 'cars/car.html', context)

@login_required
def return_car(request, rental_id):
    rental = RentalHistory.objects.get(user=request.user, id=rental_id)
    if rental.is_returned == True:
        return redirect('/users/rental_history')
    
    car = Cars.objects.get(id=rental.car.id)
    print(car.is_rented)
    if car.is_rented == False:
        messages.error(request, 'Авто не забронировано')
    else:
        car.is_rented = False
        car.save()
        rental.is_returned = True
        rental.save()

    return redirect('/users/rental_history')

def price_view(request):
    cars = Cars.objects.all()
    context = {
        'title': 'Цены на автомобили',
        'cars': cars,
    }
    return render(request, 'cars/price.html', context)

def services_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        errors = form.errors
        if form.is_valid():
            messages.success(request, 'Спасибо за обращение! Мы свяжемся с вами в ближайшее время.')
            return redirect('cars:services')
        else:
            for error in errors:
                    messages.error(request, form.errors[error])
    else:
        form = ContactForm()

    context = {
        'title': 'Наши услуги',
        'services': services,
        'form': form,
    }
    return render(request, 'cars/services.html', context)

def conditions_view(request):
    context = {
        'title': 'Условия уренды',
    }
    return render(request, 'cars/conditions.html', context)

car_rent/cars/templates/cars/about.html
{% extends 'cars/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/about.css" %}' />
{% endblock %}

{% block context %}
    <section class="welcome-section">
      <h1>О нашей компании</h1>
      <p>Мы супер!</p>
      <p>Вот и всё, что нужно знать :)</p>
    </section>

    <hr align="center" width="500" size="1" color="#336db8" />

    <section class="contacts-section">
      <h1>Контакты</h1>
      <p>+7 920 990 16 55</p>
    </section>

    <hr align="center" width="500" size="1" color="#336db8" />


    <section class="info-section">
      <h2>Часы работы</h2>
      <div class="information">
        <p>Пн - Пт: с 13:00 до 13:05</p>
        <p>Сб - Вс: Выходной</p>
      </div>
    </section>

    <hr align="center" width="500" size="1" color="#336db8" />

    <section class="map-section">
      <h2>Как нас найти</h2>
      <div class="map">
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A44ed32bc9c4c5eb68b6f0b7bd463b96664059103925d120d955c603d6105eb2d&amp;width=100%25&amp;height=600&amp;lang=ru_RU&amp;scroll=true"></script>
      </div>
    </section>
{% endblock %}

car_rent/cars/templates/cars/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %} {% endblock %}
  <link rel="stylesheet" href='{% static "css/global.css" %}' />
  {% block css %} {% endblock %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body class="light-theme">
  <div class="wrapper">
    <header class="header light-theme">
      <div><a href="{% url 'index' %}"><img src='{% static "/img/logo.png" %}' alt="logo"></a></div>

      <nav class="nav-menu light-theme">
        <a href="{% url 'cars:index' %}">Автопарк</a>
        <a href="{% url 'cars:services' %}">Услуги</a>
        <a href="{% url 'cars:price' %}">Цены</a>
        <a href="{% url 'cars:conditions' %}">Условия</a>
        <a href="{% url 'about' %}">О нас</a>
      </nav>
      <button id="themeToggle">
        <img class="img" id="img" alt="Светлая тема" src='{% static "img/icons/dark.png" %}' />
      </button>
      <div class="auth light-theme">
        {% if user.is_authenticated %}
          <div class="cart">
            <a href="{% url 'cart' %}" class="cart-btn">
              <img class="cart-img" id="cart-img" src={% static "img/icons/cart-dark.png" %} alt="Корзина">
            </a>
          </div>
          <a href="{% url 'users:profile' %}" class="profile-btn" id="profile-btn">{{ user.username }}</a>
          <a href="{% url 'users:logout' %}" class="logout-btn" id="logout-btn">Выход</a>
        {% else %}
          <a href="{% url 'users:register' %}" class="register-btn" id="register-btn">Регистрация</a>
          <a href="{% url 'users:login' %}" class="login-btn" id="login-btn">Вход</a>
        {% endif %}
      </div>
    </header>

    <div class="main">
      {% if messages %}
        <div id="popup-message" class="popup hidden">

          <div class="messages">
              {% for message in messages %}
                  <div class="alert {{ message.tags }}">
                      <span>{{ message }}</span>
                  </div>
              {% endfor %}
          </div>
        </div>
      {% endif %}
      {% block context %} {% endblock %}
    </div>
    
    <footer class="footer light-theme">
      <div class="place">
        <div><a href="{% url 'index' %}"><img src='{% static "/img/logo.png" %}' alt="logo"></a></div>
        <div>
          <p class="info">370001, Печальная область, Тоскливый район, город Грусть, проспект Разочарования, дом 13</p>
          <p class="info">Телефон: +7 (999) 999-99-99</p>
        </div>
      </div>
      <div class="social-icons">
        <a href="https://vk.com" target="_blank" class="social-icon vk">
          <img src={% static "img/icons/vkontakte.png" %} alt="VK">
        </a>
        <a href="https://facebook.com" target="_blank" class="social-icon facebook">
          <img src={% static "img/icons/facebook.png" %} alt="Facebook">
        </a>
        <a href="https://instagram.com" target="_blank" class="social-icon instagram">
          <img src={% static "img/icons/instagram.png" %} alt="Instagram">
        </a>
        <a href="https://twitter.com" target="_blank" class="social-icon twitter">
          <img src={% static "img/icons/twitter.png" %} alt="Twitter">
        </a>
      </div>
      <p class="copy">&copy; 2024 &ensp; ООО “Не ваше дело”. Все права защищены.</p>
    </footer>
  </div>

<script src={% static "js/main.js" %}></script>
</body>
</html>

car_rent/cars/templates/cars/car.html
{% extends 'cars/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/car.css" %}' />
{% endblock %}

{% block context %}
<section class="car-details-section">
    <div class="container">
        <h1>{{ car.brand.name }} {{ car.model }}</h1>
    </div>
    <div class="car-img-container">
        <div class="slider">
            <div class="slides">
                {% for image in car_images %}
                <div class="slide">
                    <img src="{{ image.image.url }}" alt="{{ car.model }}">
                </div>
                {% endfor %}
            </div>
            <div class="navigation">
                <button class="prev" onclick="moveSlides(-1)">&#10094;</button>
                <button class="next" onclick="moveSlides(1)">&#10095;</button>
            </div>
        </div>

    </div>
    <div class="">
        <div class="car-info">
            <div class="informations">
                <div class="conditions">
                    <div class="conditions-header">Условия аренды</div>
                    <div class="conditions-items">
                        <div class="condition-item">
                            <div class="condition-img">
                                <img src="{% static "img/icons/18-dark.png" %}" alt="Возраст">
                            </div>
                            <div class="condition-info">
                                <div>Возраст</div>
                                <div>от 18 лет</div>
                            </div>
                        </div>
                        <div class="condition-item">
                            <div class="condition-img">
                                <img src="{% static "img/icons/vehicle-dark.png" %}" alt="Опыт">
                            </div>
                            <div class="condition-info">
                                <div>Опыт вождения</div>
                                <div>от 3-х лет</div>
                            </div>
                        </div>
                        <a href="{% url 'cars:conditions' %}" class="conditions-more">Подробнее</a>
                    </div>
                </div>
                <div class="car-information">
                    <div class="car-information-header">Характеристики</div>
                        <p><strong>Марка: </strong> {{ car.brand }}</p>
                        <p><strong>Модель: </strong> {{ car.model }}</p>
                        <p><strong>Год выпуска: </strong> {{ car.year }}</p>
                        <p><strong>Класс: </strong> {{ car.carClass }}</p>
                        <p><strong>Цвет: </strong> {{ car.color }}</p>
                        <p><strong>Привод: </strong> {{ car.drive }}</p>
                        <p><strong>Коробка передач: </strong> {{ car.transmission }}</p>
                        <p><strong>Мощность: </strong> {{ car.power }} л.с.</p>
                        <p><strong>Объём двигателя: </strong> {{ car.engine_capacity }} л.</p>
                        <p><strong>Разгон до 100 км./ч: </strong> {{ car.acceleration }} сек.</p>
                        <br>
                        <hr width="300" size="1" color="#336db8">
                        <br>
                        <p><strong>Цена за день:</strong> {{ car.price }} руб</p>
                </div>
            </div>
            <div class="reservation">
                <form method="POST" class="rental-form light-theme" id="rental-form">
                    {% csrf_token %}
                    <label for="{{ form.start_date.id_for_label}}">Дата начала аренды</label>
                    {{ form.start_date }}
                    {{ form.non_field_errors }}
                    {{ form.start_date.errors }}
                    <label for="{{ form.end_date.id_for_label}}">Дата окончания аренды</label>
                    {% if form.end_date.errors%}
                        <div class="error">
                            {{ form.end_date }}
                        </div>
                        {{ form.non_field_errors }}
                        {{ form.end_date.errors }}
                    {% else %}
                    {{ form.end_date }}
                    {% endif %}
                    {% if car.is_rented %}
                        <button type="submit" class="rent-btn" id="rent-btn" disabled>Забронировать</button>
                    {% else %}
                        <button type="submit" class="rent-btn" id="rent-btn">Забронировать</button>
                    {% endif %}
                
                </form>
            </div>
        </div>
    </div>
    {% if car.description %}
    <div class="container">
        <div class="car-description">
            <h3>Описание</h3>
            <p>{{ car.description }}</p>
        </div>
    </div>
    {% endif %}
</section>

<script>
    const btn = document.getElementById('rent-btn');
    if ({{car.is_rented}} == True) {
        btn.setAttribute('disabled', 'disabled');
    }
    else {
        btn.removeAttribute('disabled', 'disabled');
    }
</script>
{% endblock %}

car_rent/cars/templates/cars/cars.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

car_rent/cars/templates/cars/cart.html
{% extends 'cars/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/cart.css" %}' />
{% endblock %}

{% block context %}
<section class="cart-section">
    <h1>Ваша корзина</h1>

    {% if cart_items %}
    <div class="cart-items">
        <table class="cart-table">
            <thead>
                <tr>
                    <th>Автомобиль</th>
                    <th>Цена за день</th>
                    <th>Дней аренды</th>
                    <th>Итого</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>
                        <h3>{{ item.car.brand }} {{ item.car.model }}</h3>
                        <img src="{{ item.car.image.url }}" alt="{{ item.car.model }}" class="cart-car-image">
                    </td>
                    <td>{{ item.car.price }} руб</td>
                    <td>{{ item.total_days }}</td>
                    <td>{{ item.total_price }} руб</td>
                    <td>
                        <a href="{% url 'cars:cart_delete' item.id %}" class="del-btn">Удалить</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="cart-summary">
            <h2>Общая стоимость: {{ total_price }} руб</h2>

        </div>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="checkout-btn" id="checkout-btn">Оформить аренду</button>
        </form>
        {% else %}
        <div class="cart-none">
            <p>Ваша корзина пуста.</p>
            <a href="{% url 'cars:index' %}" class="checkout-btn">Автопарк</a>
        </div>
    </div>
    {% endif %}
</section>

{% comment %} <script>
    const btn = document.getElementById('checkout-btn');
    if ({{car.is_rented}} == True) {
        btn.setAttribute('disabled', 'disabled');
    }
    else {
        btn.removeAttribute('disabled', 'disabled');
    }
</script> {% endcomment %}

{% endblock %}

car_rent/cars/templates/cars/index.html
{% extends 'cars/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/index.css" %}' />
{% endblock %}

{% block context %}
    <section class="welcome-section">
      <h1>Добро пожаловать!</h1>
      <p>Аренда автомобилей в Рязани</p>
      <p>У нас Вы всегда подберёте то, что Вам по душе!</p>
    </section>

    <hr align="center" width="500" size="1" color="#336db8" />

    <section class="services-section">
      <h2>Наши услуги</h2>
      <div class="services-list">
        {% for i in services %}
        <div class="service-item light-theme">
          <h3>{{ i.name }}</h3>
          <p>{{ i.description }}</p>
        </div>
        {% endfor %}
      </div>
      <button id="rent_btn" class="rent_btn">
        <a href="{% url 'cars:index' %}">Автопарк</a>
      </button>
    </section>
{% endblock %}

car_rent/cars/templates/cars/price.html
{% extends 'cars/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/price.css' %}">
{% endblock %}

{% block context %}
<section class="price-section">
    <h1>Цены на автомобили</h1>
    <table class="price-table light-theme" id="price-table">
        <thead>
            <tr>
                <th>Марка и модель</th>
                <th>Цена за день</th>
                <th>Действие</th>
            </tr>
        </thead>
        <tbody class="car-table">
            {% for car in cars %}
            <tr class="">
                <td>{{ car.brand.name }} {{ car.model }}</td>
                <td>{{ car.price }} руб.</td>
                <td>
                    <a href="{% url 'cars:page_car' car.id %}" class="select-btn">Заказать</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <hr align="center" width="500" size="1" color="#336db8" />


    <div class="promo-text">
        <h2>Ищете комфорт и стиль в дороге?</h2>
        <p>Аренда автомобилей с нами — это ваш путь к свободе передвижения!</p>
        <p>От путешествий по городам до деловых встреч — выберите автомобиль, идеально подходящий под ваш стиль и нужды. В нашем автопарке представлены автомобили на любой вкус: от эконом-класса до премиальных моделей, всегда в отличном состоянии и готовые к поездке.</p>
        <ul>
            <li><strong>Широкий выбор автомобилей</strong> — от надежных седанов до мощных внедорожников.</li>
            <li><strong>Удобство и простота</strong> — бронирование займет всего пару минут, а гибкие условия аренды подстроятся под ваше расписание.</li>
            <li><strong>Доступные цены</strong> — мы предлагаем конкурентные цены и выгодные условия, чтобы вы могли наслаждаться поездкой, не думая о бюджете.</li>
        </ul>
        <p>Почувствуйте свободу передвижения с нами — забронируйте автомобиль и наслаждайтесь комфортной дорогой!</p>
    </div>
</section>
{% endblock %}